### ISSUE TITLE
Installation failed because of duckdb

### ISSUE THREAD

**Issue by thomasperrein** [Bl3f/yato#4] opened 2024-08-19 12:31 UTC
When you install yato-lib on a brand new project with: 
`poetry add yato-lib`
you get
```
- Installing duckdb (0.9.2): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  /private/var/folders/tz/j2lbnhyx6w56xlfhl0ff8llc0000gn/T/tmpt__txtu2/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'tests_require'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-14.0-arm64-cpython-312
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb
  copying duckdb/filesystem.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb
  copying duckdb/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb
  copying duckdb/bytes_io_wrapper.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb
  copying duckdb/udf.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/typing
  copying duckdb/typing/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/typing
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/query_graph
  copying duckdb/query_graph/__main__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/query_graph
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/functional
  copying duckdb/functional/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/functional
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/value
  copying duckdb/value/constant.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/value
  creating build/lib.macosx-14.0-arm64-cpython-312/adbc_driver_duckdb
  copying adbc_driver_duckdb/dbapi.py -> build/lib.macosx-14.0-arm64-cpython-312/adbc_driver_duckdb
  copying adbc_driver_duckdb/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/adbc_driver_duckdb
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark
  copying duckdb/experimental/spark/exception.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark
  copying duckdb/experimental/spark/_typing.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark
  copying duckdb/experimental/spark/_globals.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark
  copying duckdb/experimental/spark/conf.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark
  copying duckdb/experimental/spark/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark
  copying duckdb/experimental/spark/context.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/catalog.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/functions.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/_typing.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/dataframe.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/conf.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/session.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/type_utils.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/types.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/readwriter.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/group.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/udf.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/streaming.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  copying duckdb/experimental/spark/sql/column.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/sql
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/errors
  copying duckdb/experimental/spark/errors/error_classes.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/errors
  copying duckdb/experimental/spark/errors/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/errors
  copying duckdb/experimental/spark/errors/utils.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/errors
  creating build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/errors/exceptions
  copying duckdb/experimental/spark/errors/exceptions/__init__.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/errors/exceptions
  copying duckdb/experimental/spark/errors/exceptions/base.py -> build/lib.macosx-14.0-arm64-cpython-312/duckdb/experimental/spark/errors/exceptions
  running egg_info
  writing duckdb.egg-info/PKG-INFO
  writing dependency_links to duckdb.egg-info/dependency_links.txt
  writing top-level names to duckdb.egg-info/top_level.txt
  interrupted
  

  at ~/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with duckdb (0.9.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "duckdb (==0.9.2)"'.
```

I'm in a virtual env of python 3.12.3, on macos Sonoma 14.6.1 (23G93)
I think you should upgrade the dependencies of duckdb to solve this issue

**Comment by Bl3f** [comment] 2024-09-15 06:33
@thomasperrein I think the issue is now fixed thanks to @MohamedBsh PR. Tell me if it's ok if you try again.

**Closed as completed by Bl3f** 2024-09-15 06:33 UTC
